services:
  api:
    container_name: books-api
    build: .
    ports:
      - 3062:8080
    working_dir: /app
    volumes: 
      - .:/app
      - ./.env:/app/.env
      - ./.air.toml:/app/.air.toml
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
    networks:
      - books-api-network
    
  db:
    image: postgres:14
    container_name: db-books-api
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    restart: 'always'
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "localhost", "-p", "5432"]
      interval: 5s
      timeout: 10s
      retries: 5
    cap_add:
      - SYS_NICE # Deve omitir alertas menores
    networks:
      - books-api-network

networks:
  books-api-network:
    driver: bridge
